### ISSUE TITLE
Parsing shorthand values can result in bad css

### ISSUE THREAD

**Issue by church29** [radkovo/jStyleParser#33] opened 2015-07-22 17:42 UTC
To reproduce:
Attempt to parse and print 
margin: 2px 0 0 0
Expected Result:
margin: 2px 0 0 0
Actual Result:
margin: 2px000

**Comment by radkovo** [comment] 2015-07-27 12:20
Hi, I'm not able to reproduce it here. Could you provide a simple test case and jStyleParser version you are using?

**Comment by church29** [comment] 2015-07-28 18:14
The issue occurs in rule.toString

**Comment by ChristophKaser** [comment] 2015-08-12 08:15
This was fixed with https://github.com/radkovo/jStyleParser/pull/23

**Closed** 2015-08-17 08:37 UTC
